{
 "title": "unbound dnscrypt",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "client queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries_tcp[5m])",
     "legendFormat": "tcp queries"
    },
    {
     "expr": "rate(encrypted_dns_client_queries_udp[5m])",
     "legendFormat": "udp queries"
    }
   ]
  },
  {
   "title": "dns client queries resolved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries_resolved[5m])",
     "legendFormat": "queries resolved"
    },
    {
     "expr": "rate(encrypted_dns_client_queries_cached[5m])",
     "legendFormat": "queries cached"
    }
   ]
  },
  {
   "title": "dns upstream sent and received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_upstream_sent[5m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(encrypted_dns_upstream_received[5m])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "dns upstream response sizes bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(encrypted_dns_upstream_response_sizes_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "dns anonymized",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_anonymized_queries[5m])",
     "legendFormat": "anonymized queries"
    },
    {
     "expr": "rate(encrypted_dns_anonymized_responses[5m])",
     "legendFormat": "anonymized responses"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "resident memory" }
   ]
  }
 ]
}