{
 "title": "plan9-dns",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "client  queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "cache hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries_cached{instance=\"127.0.0.1:9100\",job=\"node\"}[5m]) / rate(encrypted_dns_client_queries_resolved{instance=\"127.0.0.1:9100\",job=\"node\"}[5m]) * 100",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "client queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries_tcp{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "tcp"
    },
    {
     "expr": "rate(encrypted_dns_client_queries_udp{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "udp"
    }
   ]
  },
  {
   "title": "dns upstream",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_upstream_sent{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(encrypted_dns_upstream_received{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "dns upstream response sizes bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(encrypted_dns_upstream_response_sizes_bucket[5m])) by (le))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "dns anonymized",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_anonymized_queries{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "queries"
    },
    {
     "expr": "rate(encrypted_dns_anonymized_responses{handler=\"all\",instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "dnscrypt-server memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"127.0.0.1:9100\",job=\"node\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "system memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"127.0.0.1:9100\",job=\"node\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "inflight queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "encrypted_dns_inflight_tcp_queries{instance=\"127.0.0.1:9100\",job=\"node\"}",
     "legendFormat": "tcp"
    },
    {
     "expr": "encrypted_dns_inflight_udp_queries{instance=\"127.0.0.1:9100\",job=\"node\"}",
     "legendFormat": "udp"
    }
   ]
  },
  {
   "title": "offline responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(encrypted_dns_client_queries_offline{instance=\"127.0.0.1:9100\",job=\"node\"}[5m])",
     "legendFormat": "value"
    }
   ]
  }
 ]
}